<div class="hero-slider">
  <!-- 'data-glide-el="track"' is used by the Glide.js library to define the track containing all slides -->
  <div data-glide-el="track" class="glide__track">
    <!-- Container for individual slides within the slider -->
    <div class="glide__slides">

      <!-- Outputs the inner content (individual slides) for this slider -->
      <?php echo $content; ?>

    </div>

    <!-- Navigation bullets for the slider, automatically generated by Glide.js based on the number of slides -->
    <div class="slider__bullets glide__bullets" data-glide-el="controls[nav]">
    </div>
  </div>
</div>